### ISSUE TITLE
Source code does not build at all

### ISSUE THREAD

**Issue by cm0x4D** [Electrical-Age/ElectricalAge#335]
Eln.java:533: error: cannot find symbol
        stdHalfLife = config.get("battery", "batteryHalfLife", 2, "How many days it takes for a battery to decay half way").getDouble(2) \* Utils.minecraftDay;
        ^
  symbol:   variable stdHalfLife
  location: class Eln

Seems the error was introduced with commit e6f59356620b1af39d3ccba5fa8221f6557e45b1.

**Comment by cm0x4D** [comment]
@Dolu1990, @lambdaShade, @metc, @Baughn 
As we have to merge more and more pull requests, it would be useful to add a continuous integration system in order to check if the pull requests actually compile before merging them. What do you think?

**Comment by metc** [comment]
Yes, we should at least check if the code compiles without error.
Using Travis or any other CI system, if the sanity check fails, a warning is displayed before merging the PR. This would help a lot.

**Comment by Baughn** [comment]
Geh. Well, definitely a good idea. Didn't @metc setup Travis for the website just yesterday?

**Comment by Baughn** [comment]
Seems simple enough. I'll just file a bug against myself, and—
