### ISSUE TITLE
Incompatibility with newer versions of MFFS and Resonant Engine

### ISSUE THREAD

**Issue by OronDF343** [Electrical-Age/ElectricalAge#188]
Works fine with MFFS 4.1.1.61 & Resonant Engine 3.3.0.396
Crashes on startup in MFFS ~4.1.1.74 & Resonant Engine ~3.3.0.437: (also some older versions and all newer ones)
---- Minecraft Crash Report ----
// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 1/30/15 12:04 PM
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: resonant/engine/asm/StaticForwarder
    at net.minecraft.world.chunk.Chunk.func_150807_a(Chunk.java:670)
    at net.minecraft.world.World.func_147465_d(World.java:451)
    at net.minecraft.world.gen.feature.WorldGenMinable.func_76484_a(WorldGenMinable.java:78)
    at mods.eln.ore.OreDescriptor.generateSurface(OreDescriptor.java:77)
    at mods.eln.ore.OreDescriptor.generate(OreDescriptor.java:63)
    at mods.eln.server.OreRegenerate.tick(OreRegenerate.java:78)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_266_OreRegenerate_tick_ServerTickEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
    at cpw.mods.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:260)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:536)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.ClassNotFoundException: resonant.engine.asm.StaticForwarder
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(Unknown Source)
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 14 more

**Comment by BenLarge1** [comment]
I can confirm that I have this same issue after updating Resonant Engine

**Comment by DrummingFish** [comment]
Have you tried removing Electrical Age and seeing if the problem persists? Don't think it has anything to do with Electrical Age.

**Comment by BenLarge1** [comment]
I removed Resonant Engine and the crash stopped, so it's one of the two

**Comment by DrummingFish** [comment]
That doesn't answer my question. Did you try without Electrical Age? And if you removed Resonant Engine then MFFS wouldn't work. I think there's info you're not telling me.

**Comment by BenLarge1** [comment]
Just for you I added resonant engine and Mffs back and the crash happened again, so I removed Electrical Age and the crash stopped. Removed Resonant Engine and MFFS and added back Electrical Age, the crashes stopped.

**Comment by DrummingFish** [comment]
What versions of RE, MFFS and EA are you using and can you give me crash logs (on pastebin)?

**Comment by TheXWolf** [comment]
mffs-4.1.1.74-core / resonant-engine-3.3.0.437-core nothing else installed except for forge multipart 320. Get the exact same error, tested by itself on forge 1286 & 1230.

**Comment by Aroma1997** [comment]
Here's a crash log. It includes the versions of the mods used: http://pastebin.com/FRJUnXmf

**Comment by ghost** [comment]
To be honest both of theses are pretty dead...
I don't think this issue will be fixed anytime soon.

**Comment by TheXWolf** [comment]
Well people really need to look at what's going on with the mods and pay attention to the date, before Aroma posted, this topic stopped in Feb, was only open a week & half. With Nova being made and MFFS (along with everything else Cal does) being moved exclusively to Nova, I don't think people need to keep posting bugs/crashes.

**Comment by ghost** [comment]
true.

**Comment by Aroma1997** [comment]
But it still means ElectricalAge is incompatible with something (MFFS/Nova). People still may want to use these mods together.

**Comment by TheXWolf** [comment]
Yes but that's not likely to change anytime soon, electrical age is just as complex a system, and nova is still in early development, I don't think comp. is going to be first priority, it needs to be working well first. Maybe talk to ELN about that mod and see if there's a comp patch that can be made.

**Comment by Dolu1990** [comment]
Hi,

I'm note very updated with current minecraft mods ecosystem.
 About  MFFS 4.1.1.61 & Resonant Engine 3.3.0.396, this incompatibilities is strang because i don't include any API from them. and i don't have any resonant.engine.asm.StaticForwarder used in EA code.
In the stack trace, there is no eln function called.
it's strang XD

The crash open at witch moment ?

**Comment by Slaynash** [comment]
The crash append (for me) then i create a new world. I have mffs 4.1.1.74, resonant engine 3.3.0.437 and electrical age beta-1.10_r49. (1.7.10)
modpack: https://www.dropbox.com/s/qr0wlwfi0smy22p/modpack.zip?dl=1
